name: OTP Generation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 18 * * *'  # Runs the workflow every day at 18:50
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  otp-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Sets the runtime to 60 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        # No external dependencies, so this can be skipped for now
        pip install requests

    - name: Run OTP script
      run: |
        python otp_script.py &  # Run the OTP script in the background
        while true; do
          echo "OTP script is running...";
          if [ -f otp_log.txt ]; then
            cat otp_log.txt;
            git config --global user.email "deswafyfxd@outlook.com"
            git config --global user.name "deswafyfxd"
            git add otp_log.txt
            git commit -m "Update otp_log.txt"
            git push https://$ACTIONS_PAT@github.com/deswafyfxd/testnumb.git
          fi;
          sleep 10;  # Adjust time interval as needed
        done

    env:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
