name: OTP Generation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '50 18 * * *'  # Runs the workflow every day at 18:50
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  otp-generation:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Sets the runtime to 60 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run OTP script
      run: |
        python otp_script.py &  # Run the OTP script in the background
        while true; do
          echo "OTP script is running...";  # Keep the job alive
          tail -f otp_log.txt &  # Display real-time log of the OTP script
          sleep 300;  # Adjust the sleep interval as needed
        done
